#ifndef ARCH_H
#define ARCH_H

#define PSQT_FEATURES 768
#define PAWN_FEATURES 96 * 95 / 2
#define THREAT_FEATURES 59808
#define AUX_FEATURES THREAT_FEATURES + PAWN_FEATURES
#define L1_SIZE 768
#define L2_SIZE 16
#define L3_SIZE 32
#define OUTPUT_BUCKETS 8
#define KING_BUCKETS 16
#define INPUT_QUANT 255
#define L1_QUANT 128
#define INPUT_SHIFT 9

#endif
