name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        arch: [x86-64-avx2, x86-64-bmi2, x86-64-avx512]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang make

    - name: Build with ${{ matrix.compiler }} for ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          make CC=clang build=${{ matrix.arch }}
        else
          make CC=gcc build=${{ matrix.arch }}
        fi

    - name: Rename binary
      run: |
        mv Quanticade Quanticade-Linux-${{ matrix.compiler }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Quanticade-Linux-${{ matrix.compiler }}-${{ matrix.arch }}
        path: Quanticade-Linux-${{ matrix.compiler }}-${{ matrix.arch }}
        if-no-files-found: warn
